### ISSUE TITLE
Latest Dexy-Global Theme Update broke application opened indicator

### ISSUE THREAD

**Issue by kimimaru4000** [L4ki/Dexy-Plasma-Themes#1]
First off, thanks so much for your excellent themes!

I just updated to the latest version of Dexy-Global and noticed that the opened application indicator is gone from the Icons-only Task Manager in KDE Plasma.

In both of the following screenshots, Firefox is opened.

This is how it looks in Breeze Dark. Notice that there's an indication that Firefox is opened:
![Correct](https://user-images.githubusercontent.com/1388037/209246585-71dfe40b-ccfb-422a-8b72-ebfd2ba3c11f.png)

This is how it looks now after the update. Notice how there's no indication that Firefox is opened:
![Broken](https://user-images.githubusercontent.com/1388037/209246561-8c1fb24d-2c17-432e-84b9-68c6d8bcb379.png)

I hope you can help with this issue. Let me know if you need more information!

KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Display protocol: X11

**Comment by L4ki** [comment]
Hi kimimaru4000,

Thank you for your praise.
I tried in every way possible. I uninstalled Global Theme and Plasma Theme. Then I reinstall them, and everything is fine.
The files are correct.

This is how it looks with me: 
![Screenshot_20221223_090826](https://user-images.githubusercontent.com/45247573/209302034-c3f54cdb-990b-4481-bf14-fb6d5eee37f5.png)

KDE Plasma: 5.26.4
KDE Frameworks: 5.101.0


![Screenshot_20221223_094131](https://user-images.githubusercontent.com/45247573/209302979-534ff46c-3561-4524-bf4e-53ad218810d2.png)

**Comment by kimimaru4000** [comment]
Hi @L4ki, thanks! It turns out I had something cached and it wasn't working right.

Uninstalling the theme and completely deleting the desktop theme in `~/.local/share/plasma/desktoptheme/Dexy-Plasma` then reinstalling the theme fixed it. I can once again see the application opened indicators. Thanks so much!
